[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20" # Match pragma

# Enable optimizer for potential gas savings, especially important for L2s
optimizer = true
optimizer_runs = 10000 # High runs count for deployment optimization
via_ir = true # Recommended for complex logic like chess validation

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
